### ISSUE TITLE
Referencing non-existing REMIND variables; breaks remind2 tests

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/piamInterfaces#135]
https://github.com/pik-piam/piamInterfaces/blob/b287de5e582d9066af682eb41d1914c666997a28/inst/templates/mapping_template_NAVIGATE.csv#L895-L898

`FE|Transport|LDV|Liquids`, `FE|Transport|LDV|Gases`, `FE|Transport|LDV|Electricity`, and `FE|Transport|LDV|Hydrogen` don't exist, but `FE|Transport|LDV|+|Liquids`, `FE|Transport|LDV|+|Gases`, `FE|Transport|LDV|+|Electricity`, and `FE|Transport|LDV|+|Hydrogen` do
https://github.com/pik-piam/remind2/blob/fcd6fcf6f63086355d39c806d96862a726f4e8f7/R/reportFE.R#L955-L958

**Comment by strefler** [comment]
They do exist in the coupled mifs. I guess one would have to use the mifs without plus then for standalone runs. Also, I just checked my runs which used a snapshot from May, and there FE|Transport|LDV|Liquids etc. did exist as well.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
pik-piam/remind2 problem then.

**Comment by fbenke-pik** [comment]
@strefler if the test fails, but the variables are produced in principle, we might just use an inappropriate gdx files for the test. can you point me to a recent gdx that should have all REMIND vars needed for a NAVIGATE submission, so i can incorporate it into the test?

**Comment by fbenke-pik** [comment]
This warning is produced because the variables are created by EDGE-T, not remind2 standard reporting, and therefore should be excluded from the NAVIGATE test. Should be fixed with [this PR](https://github.com/pik-piam/piamInterfaces/pull/139).
