### ISSUE TITLE
Recursive support for summation checks

### ISSUE THREAD

**Issue by Renato-Rodrigues** [pik-piam/piamInterfaces#142]
Assume a `summationsFile` containing these summation checks:

parent | child
-- | --
Primary Energy | Primary Energy\|non-Fossil
Primary Energy | Primary Energy\|Fossil
  |  
Primary Energy\|Fossil | Primary Energy\|Coal
Primary Energy\|Fossil | Primary Energy\|Gas
Primary Energy\|Fossil | Primary Energy\|Oil

If the mif file provided to piamInterfaces::checkSummations does not contain the variable `Primary Energy|Fossil`, the summation for `Primary Energy` would not be tested, even if it could be obtained by the summation of `Primary Energy|Coal`, `Primary Energy|Gas` and `Primary Energy|Oil`.

**Feature request:** 
- Whenever a variable is missing in a summation check, check if the variable can be obtained from another summation defined in the `summationsFile`, and use its value if it contains some information.
- This could be added as an extra option to the function, possible enabled by default: e.g. `recursive = true`.

**Alternative potential implementation:**
- Create a function in piamInterfaces to fill missing variables based on the `summationsFile` groups (e.g. `fillMissing` function).
- Run this function inside `checkSummations` before executing the summation checks.
- Pros: the `fillMissing` function can be useful for other use cases also.
- Cons: It can increase dimensionality of summation checks, and/or be incompatible with summation groups that include redundant (duplicated) information in different variables of the same summation group. The latter can be avoided by adding additional alternative summation groups as in https://github.com/pik-piam/piamInterfaces/pull/141

**Comment by fbenke-pik** [comment]
Thanks for your input, Renato. Definitely can look into this, but need some additional input on how urgent / frequent this use case is so I can prioritize the task. 
Any thoughts @Renato-Rodrigues @orichters @LaviniaBaumstark ?

**Comment by Renato-Rodrigues** [comment]
I can describe my use case to inform your decision:
@robertpietzcker  is currently working on a model comparison for ECEMF, which includes bottom-up and IAM models that are not able to report the same set of variables.
We need to make sure that results from these models are consistent and this feature would allow using piamInterfaces to do summation checks for those other models.

**Comment by orichters** [comment]
I don't need this feature for our NGFS model comparison and rather prefer to have summation checks fail if some variables are missing, such that I can tell the other modeling team to add it. I would also prefer that `recursive = FALSE` remains the default that we use for checking our REMIND submissions. This is of course no opposition to implementing such a feature.

One question: If for example `PE|Fossil` is `PE|Fossil|w/ CCS` + `PE|Fossil|w/o CCS` but also `PE|Fossil|Coal` + `PE|Fossil|Gas`. Now, if `PE` = `PE|Fossil` + `PE|Renewable`, should the recursive mode check both of them?

**Comment by Renato-Rodrigues** [comment]
I have nothing against this not being the default enabled option. Asking for other modelling groups to add missing variables although is neither an option or just takes too long to realize in our case.

About the summation question, I would say it would depend of the summation groups you define.
If you define the summations:
```
PE|Fossil = PE|Fossil|w/ CCS + PE|Fossil|w/o CCS
PE|Fossil 2 = PE|Fossil|Coal + PE|Fossil|Gas + PE|Fossil|Oil
PE = PE|Fossil + PE|Renewable
```
I would assume that the summation check would need to:
(1) for any missing variable, replace it with a non-zero value if the variable is a result of another summation and issue a warning in the log file for that. You can simply add to `PE|Fossil` the value of the first non-zero summation in this case.   
(2) check for all above summations after missing variables are filled and issue an error if the summations doe not check;
(3) check if alternative summations for the same variable provide the same value (e.g. `PE|Fossil` and `PE|Fossil 2` above) and issue an error if both are non-zero and have different values.

**Comment by fbenke-pik** [comment]
The discussion already shows how complex implementing such a feature is due to all the border cases.

> .. is currently working on a model comparison for ECEMF, which includes bottom-up and IAM models that are not able to report the same set of variables.
We need to make sure that results from these models are consistent and this feature would allow using piamInterfaces to do summation checks for those other models.

For this use case, I would 
1. Check the submissions per model for completeness of the variables (sth similar as in [this example](https://gitlab.pik-potsdam.de/REMIND/miptemplate/-/blob/master/template.Rmd#validate-data)). 
2. Then calculate the missing variables ([an example from Ariadne](https://gitlab.pik-potsdam.de/REMIND/ariadne/-/blob/master/scenario_group/commons/calcAdditionalVars.R))
3. Then run checkSummations as is.

Step 1 and 2 might not be feasible if we are talking about large gaps with many missing variables across all the models, but it should be fine for smaller gaps.

**Comment by Renato-Rodrigues** [comment]
My suggestion on the first post was to exactly create the function you are mentioning: see `fillMissing` mention above.

Supporting this in the checkSummations code is necessary for the case of contradictory alternative summation groups, if this is not handled already in the checkSummations code.
 
The implementation shouldn't be more complex than: 

1. add a parameter to the function `checkSummations` called `recursive`.
2. if `recursive = TRUE`
2.1 call the `fillMissing` function to fill the gaps on data
2.2 add a warning to the log file if two group summations for the same variable does not sum up to the same value: e.g. `PE|Fossil` <> `PE|Fossil 2` (if this is not in place already as one of the checkSummation tests).
2.3 if two summations have different values (e.g. `PE|Fossil 2` > `PE|Fossil` <> 0), or if only an alternative summation has value (e.g. `PE|Fossil 2` <> 0 and `PE|Fossil 2` = 0), choose the one with value (or in the first case maybe the one with the biggest value) and rename it to have the clear variable name: e.g. rename `PE|Fossil 2` to `PE|Fossil` in this case.
3. run the summations check code as it is now.

**Comment by Renato-Rodrigues** [comment]
Defining by hand a project specific validation data, while alternatively we could use the group summations file to do exactly the same based in an automated way seams too much double work to me.

**Comment by orichters** [comment]
Renato, what I haven't understood yet is: In the end, do you also want the data with gaps filled saved or returned or do you just want the summation check results?

If I understand it correctly, the question is whether you call
```
checkSummations(data, summationsFile = "AR6", fillMissing = TRUE, …)
```
which calls `fillMissing()` itself or
```
checkSummations(fillMissing(data, summationsFile = "AR6"), summationsFile = "AR6", …)
```
To avoid redundancy, I would opt for the first.

2.2 is not yet implemented, but I also don't think this is an important feature for the non-recursive ones, because if `PE` = `PE|Fossil` + `PE|Renewable` and `PE 2` = `PE|w/ CCS` + `PE|w/o CCS` have different values, as you have a unique `PE` value in the data, at least one of them will fail. So I would probably follow the suggestion to put 2.2 and 2.3 into the fillMissing function.

**Comment by Renato-Rodrigues** [comment]
It does not matter for my current use case to have access or not for the "filled" data. 
However, having the `fillMissing` function as an independent function is both a more elegant solution in my opinion and could also be proven useful in the future.

Anyway, I have no strong opinion on integrating this directly into the checkSummations function or calling sequentially the `fillMissing` and only then `checkSummations` functions, as long as 2.2 and 2.3 are considered for any of the solutions.
