### ISSUE TITLE
checkSummation plots do not include totals for multiple summations cases of the same variable

### ISSUE THREAD

**Issue by Renato-Rodrigues** [pik-piam/piamInterfaces#180]
Reproduction:

Consider two group summations like for example:
- group 1:
```
Emissions|Kyoto Gases;Emissions|Kyoto Gases|Industrial Processes;1
Emissions|Kyoto Gases;Emissions|Kyoto Gases|Energy;1
Emissions|Kyoto Gases;Emissions|Kyoto Gases|Waste;1
Emissions|Kyoto Gases;Emissions|Kyoto Gases|Other;1
Emissions|Kyoto Gases;Emissions|Kyoto Gases|AFOLU;1
Emissions|Kyoto Gases|AFOLU;Emissions|Kyoto Gases|AFOLU|Agriculture;1
Emissions|Kyoto Gases|AFOLU;Emissions|Kyoto Gases|AFOLU|Land;1
Emissions|Kyoto Gases|Energy and Industrial Processes;Emissions|Kyoto Gases|Industrial Processes;1
Emissions|Kyoto Gases|Energy and Industrial Processes;Emissions|Kyoto Gases|Energy;1
```

- group 2:
```
Emissions|Kyoto Gases 2;Emissions|F-Gases;1
Emissions|Kyoto Gases 2;Emissions|N2O;0.265
Emissions|Kyoto Gases 2;Emissions|CH4;28
Emissions|Kyoto Gases 2;Emissions|CO2;1
```

Summation deviations charts will be created perfectly in the pdf for the first group.
However, the chart for the second group will have the total black line missing, most probably because the total variable passed to the `showAreaAndBarPlots` function in the following line is `Emissions|Kyoto Gases 2` instead of `Emissions|Kyoto Gases`.

https://github.com/pik-piam/piamInterfaces/blob/011e72eab3a580371a5fdfcce686eaec1ff42014/R/checkSummations.R#L207

**Comment by Renato-Rodrigues** [comment]
My work-around locally was to add `gsub(" [1-9]$", "", p)`, instead of `p` in the function call to fix the issue, but I am not sure if you have a more elegant solution for that.

**Comment by fbenke-pik** [comment]
Had a look and don't think there is a more elegant way to fix that issue, so created a PR here:
https://github.com/pik-piam/piamInterfaces/pull/181
