### ISSUE TITLE
generate plots charts in checkSummations do not consider the factor values defined at the summation_groups_*.csv file

### ISSUE THREAD

**Issue by Renato-Rodrigues** [pik-piam/piamInterfaces#213]
# Issue:

-  The pdf report charts created using `checkSummations` and `generatePlots = TRUE` do not consider the factors defined in the summation check tables (summation_groups_*.csv).

# Reproduction:

- The ECEMF summation check for total GHG is defined as `Emissions|Kyoto Gases 2` = 28 * `Emissions|CH4` + `Emissions|CO2` + `Emissions|F-Gases` + 0.265 * `Emissions|N2O`

https://github.com/pik-piam/piamInterfaces/blob/c727b5e45e5f432198b1b9774b2e64f9f6d76c2d/inst/summations/summation_groups_ECEMF.csv#L37-L40

- The values at the summation csv are presented correctly:

model | scenario | region | period | variable | unit | value | checkSum | diff | reldiff | details
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
IMAGE | WP1 NetZero | EU27 & UK (*) | 2005 | Emissions\|Kyoto Gases 2 | Mt CO2e/yr | 5892.23413 | 5917.05777 | 24.8236421 | 0.4 | 28 * Emissions\|CH4 (23.5059933662415) + Emissions\|CO2 (4765.56206810088)   + Emissions\|F-Gases (126.401477813721) + 0.265 * Emissions\|N2O   (1384.62797290641)

- However the chart use the values before the conversion factors are applied, as it can be seen below in the much smaller CH4 values and the much higher N2O values:

![image](https://github.com/pik-piam/piamInterfaces/assets/33692508/62526ac3-ced2-4408-89a9-925dcbd420e9)

**Comment by orichters** [comment]
I had a short look. That requires a major refactoring it seems, because the information about these factors is not really available at this point in the script. Is that urgent? Maybe also @fbenke-pik can weigh in, I think he implemented the calculations, if I remember correctly.

**Comment by Renato-Rodrigues** [comment]
Thks for taking a look @orichters!

I can live with this bug for now, so it is not a high priority. Just don't let it go completely forgotten :)

**Comment by Renato-Rodrigues** [comment]
tested and working perfectly. Thank you!
