### ISSUE TITLE
Inconsistency in emission variables

### ISSUE THREAD

**Issue by pweigmann** [pik-piam/piamInterfaces#214]
I received feedback that we are inconsistent in our NGFS runs wrt. the variable `Emissions|CO2|Energy and Industrial Processes`. It does not form the sum of `...Energy` and `...Industrial Processes` as one would expect. I could track this down to the mapping template, where `Emissions|CO2|Energy` also includes the carbon management variables for carbon capture and carbon storage, see [here](https://github.com/pik-piam/piamInterfaces/blame/c727b5e45e5f432198b1b9774b2e64f9f6d76c2d/inst/templates/mapping_template_AR6.csv#L301) or in the picture below.

@strefler do you know whether this is correct? And if yes - it seems we are not doing it in the same way on the REMIND reporting side, where only used carbon is subtracted (if I understand correctly what is happening [here](https://github.com/pik-piam/remind2/blob/b42b0baa8179ee55b13b2454ef703e1f73564737/R/reportEmi.R#L1116)). The way I see it, `Emissions|CO2|Energy` means something different than our REMIND `Emi|CO2|Energy` but within `Emissions|CO2|Energy and Industrial Processes` we treat them as if they were the same, resulting in the inconsistency. Do you have an idea what to do?

![image](https://github.com/pik-piam/piamInterfaces/assets/28896133/81fe49c9-6f52-4560-8cbf-ad2291365467)

**Comment by strefler** [comment]
I don't really know. Emissions|CO2|Energy and Emissions|CO2|Industrial Processes should definitively add up to Emissions|CO2|Energy and Industrial Processes, so if that's not the case something is wrong. However, I can't say where the mistake is, that depends on the definition of vm_emiTeMkt. If that excludes emissions from synthetic fuels, then these would be added with the Carbon Management variables. @Renato-Rodrigues or @fschreyer might know more

**Comment by fschreyer** [comment]
``Emi|CO2|+|Energy`` include CCU flows, see [here](https://github.com/pik-piam/remind2/blob/ddcedbbc256cc69850a43903b3ecaa5740acf0c3/R/reportEmi.R#L466), while vm_emiTeMkt does not. So, I would say the NGFS mapping is wrong. You do not need to add carbon usage to the energy emissions variable as it is already contained / taken care of (not all CCU is accounted under energy; we account CCU at the CO2 provider).

**Comment by pweigmann** [comment]
Thanks Felix! If there are no objections (@strefler @amerfort ?) I will remove the Carbon Management variables from the summations. Originally, they were added by Silvia, almost 3 years ago to avoid inconsistencies (see [here](https://github.com/pik-piam/project_interfaces/commit/47d5be8ab4fc04034d2f12f9640e5b345f1b9190) ) but it seems our reporting changed at some point.
