### ISSUE TITLE
Add new energy waste emissions to mapping templates to ensure summation consistency in projects

### ISSUE THREAD

**Issue by fschreyer** [pik-piam/piamInterfaces#241]
New energy emissions variables for waste were added to REMIND with the feedstocks implementation ([reporting added in this PR](https://github.com/pik-piam/remind2/pull/489)) such that energy emissions now sum as

``Emi|CO2|+|Energy`` = ``Emi|CO2|Energy|+|Supply`` + ``Emi|CO2|Energy|+|Demand`` + ``Emi|CO2|Energy|+|Waste``,
``Emi|GHG|Energy`` = ... etc. 

The project mapping files still need to be adapted to this change to ensure summation consistency of IIASA submissions. 

The question where to put this to ensure consistency in projects, which do not have this variable structure. Looking, for instance, at the NAVIGATE template (which I understand to be the most up-to-date IAMC template), I think we need to decide whether we map the waste emissions either to energy supply or demand as that's the distinction they have. Assuming that most of the waste goes to power or heating plants, one approach would be to map it to ``Emissions|CO2|Energy|Supply|Other``. This has the following definition in NAVIGATE:

```
CO2 emissions from fuel combustion in other energy supply sectors (please provide a definition of other sources in this category in the 'comments' tab)
```
So, it seems to be a rather flexible category. Just a suggestion. Main thing is that it gets accounted somewhere. 

Tagging @mellamoSimon, @strefler. Also @orichters as someone who seems experienced with ``piamInterfaces``.

**Comment by robertpietzcker** [comment]
I don't find this proposal plausible - the emissions from waste burning should be INSIDE both the Energy|Supply and Energy|Demand tree, not separate. They are an input to a CHP plant or an industry factory, so their emissions will be monitored and attributed to the CHP plant or the industry factory, but not separate.

**Comment by mellamoSimon** [comment]
hi. did you eventually meet to discuss this? did I miss any updates? thanks!

**Comment by fschreyer** [comment]
We did not resolve this. But we need to. Can we do a meeting to discuss and hand over to the next person responsible?

**Comment by mellamoSimon** [comment]
let's try next week: https://dud-poll.inf.tu-dresden.de/anonymous/rXcfS1sI1A/

**Comment by orichters** [comment]
I have no strong opinion on this, so will not join the meeting, but would intuitively side with Robert that it should be part of any of the two categories.

**Comment by fschreyer** [comment]
Thanks for setting this up. But sry for insisting on this and please let me know if I am just not well informed. I would like to actually have a broader meeting with all people involved in the industry team and around of Falko, Jakob, Michaja, and then maybe Gunnar and Jess to clarify to whom to talk to for future (potential ;-)) issues related to feedstocks and who will implement next steps there. 

I do not see much benefit if Simon, Robert and I meet and agree that it needs more implementation and nobody wants to do it.

**Comment by orichters** [comment]
So for AR6, like that, @fschreyer? Any other variable, that needs to be adjusted?
```
idx;variable;unit;piam_variable;piam_unit;piam_factor;piam_spatial;internal_comment;Comment;Definition;source
;Emissions|CO2|Energy;Mt CO2/yr;Emi|CO2|Energy|+|Waste;Mt CO2/yr;1;;;;;Rx
;Emissions|CO2|Energy|Supply;Mt CO2/yr;Emi|CO2|Energy|+|Waste;Mt CO2/yr;0.8;;;;;Rx
;Emissions|CO2|Energy|Supply|Other Sector;Mt CO2/yr;Emi|CO2|Energy|+|Waste;Mt CO2/yr;0.8;;;;;Rx
;Emissions|CO2|Energy|Demand;Mt CO2/yr;Emi|CO2|Energy|+|Waste;Mt CO2/yr;0.2;;;;;Rx
;Emissions|CO2|Energy|Demand|Other Sector;Mt CO2/yr;Emi|CO2|Energy|+|Waste;Mt CO2/yr;0.2;;;;;Rx
```

**Comment by orichters** [comment]
Is somebody working on fixing that in remind2?

**Comment by fschreyer** [comment]
I am. So far, I have not found the time. Will give updates [here](https://github.com/remindmodel/development_issues/issues/261). So, this can be closed.
