### ISSUE TITLE
Variables with wrong piam_unit are just silently dropped instead of an error/warning raised

### ISSUE THREAD

**Issue by orichters** [pik-piam/piamInterfaces#250]
```
qe <- quitte::quitte_example_data %>%
  filter(.data$variable %in% c("Consumption", "Population")) %>%
  droplevels()

AR6 <- qe %>%
  mutate(unit = factor(ifelse(.data$variable == "Consumption", "quadrillion", as.character(.data$unit)))) %>%
  generateIIASASubmission(mapping = "AR6", outputFilename = NULL) %>%
  as_tibble()

message("qe: ", paste(levels(qe$variable), collapse = ", "),
        ". AR6: ", paste(levels(AR6$variable), collapse = ", "))
```
had to correct it here when I noticed some variables were missing:
https://github.com/pik-piam/piamInterfaces/pull/249/commits/e93480a8ffcb118f00ace25abee40efe807c51ce

**Comment by orichters** [comment]
Can we make the mapping [here](https://github.com/pik-piam/piamInterfaces/blob/6d875b4aa10866b78fb16e7bdbf54f67ac598a12/R/generateIIASASubmission.R#L149) based on `piam_variable` alone, and then afterwards take the data and warn for all cases where `unit` and `piam_unit` are not identical, and then drop `piam_unit`?

**Comment by fbenke-pik** [comment]
> Can we make the mapping [here](https://github.com/pik-piam/piamInterfaces/blob/6d875b4aa10866b78fb16e7bdbf54f67ac598a12/R/generateIIASASubmission.R#L149) based on `piam_variable` alone, and then afterwards take the data and warn for all cases where `unit` and `piam_unit` are not identical, and then drop `piam_unit`?

Should be cases where `piam_unit` in mifs and `piam_unit` in templates are not equal, right?

**Comment by orichters** [comment]
Yes, exactly! The case where iiasatemplate and our mapping template is different is already covered.

By the way: For the variables from remind2, we would probably have noticed it somewhat late based on the tests there.
