### ISSUE TITLE
Industry|Heat variables

### ISSUE THREAD

**Issue by orichters** [pik-piam/piamInterfaces#263]
Dear industry colleagues, the `AR6` template expects the following variables to exist in remind2 reporting, which doesn't seem to be the case:
```
FE|Industry|Heat|Cement
FE|Industry|Heat|Chemicals
FE|Industry|Heat|Steel
```

I found `FE|Industry|Chemicals|Heat` (different order), but nothing for Cement and Steel.

Should I replace what exists, and remove the other?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
You can remove all of them.  REMIND assumes industry to consume all `Heat` in the other industry subsector.  `FE|Industry|Heat|Chemicals` was added by mistake and is zero anyhow.

**Comment by orichters** [comment]
ok, I will remove all from both remind2 and piamInterfaces
