### ISSUE TITLE
Initial Setup of piam_interfaces

### ISSUE THREAD

**Issue by fbenke-pik** [pik-piam/piamInterfaces#3]
- [x] migrate all relevant functionality and templates from project_interfaces
- [x] decide: unify template structure?
   - Rename the `r30m44*` variables to `remmag` or so?
   - streamline AR6 template and delete all old mappings?
- [x] refactor function `generateIIASASubmission`
- [x] refactor function `generateMappingFile`
- [x] write check functions to be called in remind2 to assure that variable renamings don't cause problems
- [x] write tests in remind2 to assure that variable renamings don't cause problems
   - [x] SHAPE
   - [x] NGFS
   - [x] AR6
   - [x]  NAVIGATE
- [x] README and documentation
- [x] [tutorial in remindmodel](https://github.com/remindmodel/remind/blob/develop/tutorials/13_Submit_to_IIASA_database.md)
- [x] set up interface with [xlsx_IIASA.R](https://github.com/remindmodel/remind/blob/develop/scripts/output/export/xlsx_IIASA.R) scripts in remindmodel such that export documents can be generated using output.R --> https://github.com/remindmodel/remind/pull/1016
- [x] migrate ARIADNE template to this library
- [x] migrate ECEMF template to this library

**Comment by orichters** [comment]
Is done, right?

**Comment by fbenke-pik** [comment]
Yes
