### ISSUE TITLE
piam_weight column mix of NA and "NULL"

### ISSUE THREAD

**Issue by robinhasse** [pik-piam/piamInterfaces#322]
The following code
```R
piamInterfaces::generateIIASASubmission(
  "/p/tmp/krekeler/aux/floorSpaceFix/output/REMIND_generic_Base_withoutPlus_floorSpaceFix.mif",
  "/p/tmp/krekeler/aux/floorSpaceFix/mappings/mapping_CAMPAIGNers_Build.csv"
)
```
throws this error:
```
Error in `if (all(dataframe$piam_weight == "NULL") || all(is.na(dataframe$piam_weight))) ...`:
! missing value where TRUE/FALSE needed
```
In my case, `dataframe$piam_weight` is a mix of `"NULL"` and `NA` (which I suppose it shouldn't be). I any case, I think that the line should be changed to
```R
if (all(isTRUE(dataframe$piam_weight == "NULL")) || all(is.na(dataframe$piam_weight)))
```
to handle `NA` but I think that there were more issues. Unfortunately, I didn't have the time to follow up on this (submission is overdue) so I downgraded to `0.19.0` which worked for me. That's why I just leave the error report here.

**Comment by jdrtommey** [comment]
Hey, sorry about this bug, I will look into it.

**Comment by robinhasse** [comment]
> Hey, sorry about this bug, I will look into it.

No worries, thank you!

**Comment by orichters** [comment]
@jdrtommey: Any progress on that?
