### ISSUE TITLE
question about Final Energy|Transportation|Liquids variables

### ISSUE THREAD

**Issue by orichters** [pik-piam/piamInterfaces#39]
In [this PR](https://github.com/pik-piam/piamInterfaces/pull/21/files#diff-91b7c8603004cecca623def25ab2a7a465b9211f16f394a5a646d526396befaa), I took out the following summation group:
```
Final Energy|Transportation|Liquids = 
  Final Energy|Transportation|Liquids|Bioenergy
+ Final Energy|Transportation|Liquids|Coal
+ Final Energy|Transportation|Liquids|Fossil synfuel
+ Final Energy|Transportation|Liquids|Natural Gas
+ Final Energy|Transportation|Liquids|Oil
```
But maybe this was an error and it should rather be fixed on the reporting side, not by deleting it here? Maybe @johannah-pik, at some point in the future, you can have a look? (Sorry for putting work on you, again)

**Comment by johannah-pik** [comment]
Hi Oliver,
could you provide me the REMIND var names equivalents?

**Comment by orichters** [comment]
```
### Results from template: mapping_template_AR6.csv
# Export variable groups found in summation_groups_AR6.csv          # Corresponding piam_variable variables
. Final Energy|Transportation|Liquids (EJ/yr) =                    . FE|Transport|+|Liquids (EJ/yr) =
  + Final Energy|Transportation|Liquids|Bioenergy                     + FE|Transport|Liquids|+|Biomass
  + Final Energy|Transportation|Liquids|Coal                          + FE|Transport|Liquids|Fossil|+|Coal
  + Final Energy|Transportation|Liquids|Fossil synfuel                + NA
  + Final Energy|Transportation|Liquids|Natural Gas                   + FE|Transport|Liquids|Fossil|+|Gas
  + Final Energy|Transportation|Liquids|Oil                           + FE|Transport|Liquids|Fossil|+|Oil
Units: EJ/yr                                                        Units: EJ/yr
```

**Comment by johannah-pik** [comment]
Thanks :) Is Final Energy|Transportation|Liquids (EJ/yr) supposed to be with or without bunkers (=international transport)?

**Comment by orichters** [comment]
The definition says: "final energy consumption by the transportation sector of refined liquids (conventional & unconventional oil,biofuels,coal-to-liquids,gas-to-liquids)". Well, so I don't know. @christophbertram, can you say that?

**Comment by christophbertram** [comment]
It's not specified so hard to say. We could check whether the regional data adds up to the global in GCAM and MESSAGE. If they do so, then we should also include bunkers, if not, not...

**Comment by orichters** [comment]
I guess the reason is that  `Final Energy|Transportation|Liquids|Hydrogen` does not exist in the templates, I added it here: #132
